---
- name: check if {{ nexus_data_dir }}/etc/nexus.properties file is present
  ansible.builtin.stat:
    path: "{{ nexus_data_dir }}/etc/nexus.properties"
  register: nexus_properties_file
  tags: nexus-postgresql

- name: Create {{ nexus_data_dir }}/etc directory
  ansible.builtin.file:
    state: directory
    path: "{{ nexus_data_dir }}/etc"
    owner: "{{ nexus_os_user }}"
    group: "{{ nexus_os_group }}"
    mode: "0750"
  when: nexus_properties_file.stat.exists == false
  tags: nexus-postgresql

- name: Create {{ nexus_data_dir }}/etc/nexus.properties file
  ansible.builtin.file:
    state: touch
    dest: "{{ nexus_data_dir }}/etc/nexus.properties"
    owner: "{{ nexus_os_user }}"
    group: "{{ nexus_os_group }}"
    mode: "0640"
  when: nexus_properties_file.stat.exists == false
  tags: nexus-postgresql

# copy file to target
- name: Copy the license file to the target
  ansible.builtin.copy:
    src: "license.lic"
    dest: "{{ nexus_data_dir }}/etc/license.lic"
    owner: "{{ nexus_os_user }}"
    group: "{{ nexus_os_group }}"
    mode: "0640"
  tags: nexus-postgresql

- name: Store license in {{ nexus_data_dir }}/etc/nexus.properties file
  ansible.builtin.lineinfile:
    path: "{{ nexus_data_dir }}/etc/nexus.properties"
    line: "nexus.licenseFile={{ nexus_data_dir }}/etc/license.lic"
    firstmatch: true
    insertafter: "EOF"
    state: present
  tags: nexus-postgresql
